version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./html:/usr/share/nginx/html
    container_name: hello-world-web
    labels:
      caddy: portainer-test.nicolasyates.com
      caddy.reverse_proxy: "localhost:8088"
